# Generated by Django 6.0.4 on 2026-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField()),
                ('brand', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('transmission', models.CharField()),
                ('engine_volume', models.CharField()),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField()),
                ('image', models.CharField()),
            ],
        ),
    ]
