# Generated by Django 6.0.4 on 2026-04-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='image',
            new_name='imag',
        ),
    ]
