# Generated by Django 6.0.4 on 2026-04-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0002_rename_image_mahsulot_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='imag',
            new_name='image',
        ),
    ]
