# Generated by Django 6.0.4 on 2026-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0003_rename_imag_mahsulot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='instagram_user',
            field=models.CharField(default='rustamovv.09', help_text='Instagram username', max_length=100),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='owner_phone',
            field=models.CharField(default='+998901234567', max_length=20),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='telegram_user',
            field=models.CharField(default='Rustamovv_E', help_text="Telegram username (@'siz yozing)", max_length=100),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='engine_volume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
    ]
