# Generated by Django 6.0.4 on 2026-05-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0004_alter_mahsulot_options_mahsulot_instagram_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='image',
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='instagram_user',
            field=models.CharField(default='rustamovv.09', max_length=100),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='telegram_user',
            field=models.CharField(default='Rustamovv_E', max_length=100),
        ),
    ]
