# Generated by Django 6.0.4 on 2026-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0005_remove_mahsulot_image_alter_mahsulot_instagram_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
