# Generated by Django 6.0.4 on 2026-05-07 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0006_mahsulot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
